#!/bin/bash

## Description: Sync the local site with dev environment
## Usage: refresh
## Example: ddev refresh

set -ev

echo "Authorize ssh keys in docker containers.."
ddev auth ssh

echo "Executing composer install.."
ddev composer install

# echo "Pull database from remote environment.."
# ddev pull PROVIDER_NAME_HERE

echo "Apply the updates to current database.."
ddev drush deploy -y --no-interaction

echo "Execute frontend"
ddev frontend
